package assets.enums;

public enum FightOutcomeType {
    PLAYER_LOSES_MONSTER_BUT_BATTLE_CONTINUES,
    PLAYER_OUT_OF_MONSTERS_AND_LOSES_BATTLE_GAME_OVER,
    PLAYER_WINS_BATTLE,
    BOTH_MONSTERS_STILL_HAVE_HEALTH
}
